name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Tag Name
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag=${TAG_NAME}" >> $GITHUB_ENV

      - name: Dispatch PHP SDK
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: kodypay/kody-clientsdk-php7
          client-payload: '{"tag": "${{ env.tag }}", "repository": "${{ github.repository }}"}'
          event-type: tag-push
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
